/*
 * Copyright (c) 2025, BlackBerry Limited. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef MCP25xxFD_PLATFORM_H_
#define MCP25xxFD_PLATFORM_H_

/**
 * @file
 *
 * Abstract the HW platform the driver is running on.
 *
 * The driver requires HW level access to the IRQ generated by the MCP25xxFD.
 * Normally this comes in through a GPIO line but that doesn't have to be
 * the case.
 *
 * Managing this is HW platform dependent so this exists as an abstraction
 * from the specifics of the actual HW.
 */

#include <stdint.h>

/**
 * Initialize the platform support.
 *
 * This MUST be called before any of the other platform APIs,
 * other than deinitialize(), are called.
 *
 * May be called more than once. If so, just return EOK if the
 * platform is already successfully initialized.
 *
 * @return EOK(0) if successful, one of the other errno codes on failure.
 */
typedef int (*mcp25xxfd_platform_initialize_t)(void);

/**
 * Deinitialize the platform support.
 *
 * Calling this API when the platform support is NOT initialized is ok
 * and results in a no-op.
 */
typedef void (*mcp25xxfd_platform_deinitialize_t)(void);

/**
 * Set up the desired GPIO to work as an interrupt.
 *
 * @param[in]   gpio    The GPIO to set up.
 *
 * @return EOK(0) if successful, one of the other errno codes on failure.
 */
typedef int (*mcp25xxfd_platform_setup_gpio_t)(uint32_t gpio);

/**
 * Get the IRQ number associated with a GPIO.
 *
 * @param[in]   gpio    The GPIO to get the IRQ for.
 *
 * @return The positive number for the IRQ associated with the GPIO
 *         If there is an error -1 will be returned.
 */
typedef int (*mcp25xxfd_platform_gpio_irq_get_t)(uint32_t gpio);

/**
 * Checks if the IRQ associated with a GPIO is active.
 *
 * @param[in]   gpio    The GPIO with the associated IRQ to check.
 *
 * @return True (non-zero) if the IRQ is active (it has fired).
 *         False (zero) if the IRQ is inactive (it has NOT fired).
 */
typedef int (*mcp25xxfd_platform_gpio_irq_active_t)(uint32_t gpio);

/**
 * Clears the IRQ associated with a GPIO, making it inactive.
 *
 * @note If the conditions that caused the IRQ to go active have not yet been
 *       cleared, then the IRQ may immediately go active again.
 *
 * @param[in]   gpio    The GPIO with the associated IRQ to clear.
 */
typedef void (*mcp25xxfd_platform_gpio_irq_clear_t)(uint32_t gpio);


/**
 * Function pointers and state for platform support.
 *
 * See the doxygen for details on the individual functions
 */
struct mcp25xxfd_platform {
    mcp25xxfd_platform_initialize_t initialize;
    mcp25xxfd_platform_deinitialize_t deinitialize;
    mcp25xxfd_platform_setup_gpio_t setup_gpio;
    mcp25xxfd_platform_gpio_irq_get_t gpio_irq_get;
    mcp25xxfd_platform_gpio_irq_active_t gpio_irq_active;
    mcp25xxfd_platform_gpio_irq_clear_t gpio_irq_clear;
};
typedef struct mcp25xxfd_platform mcp25xxfd_platform_t;

/*
 * The known platforms we support
 */
extern const mcp25xxfd_platform_t Mcp25xxfdPlatformRpi4;
extern const mcp25xxfd_platform_t Mcp25xxfdPlatformRpi5;
extern const mcp25xxfd_platform_t Mcp25xxfdPlatformGeneric;

#endif  // MCP25xxFD_PLATFORM_H_
