# Update /system/etc/config/spi/spi.conf
# Note SPI3 is used for camera and should be left untouched.
[bus]
busno=0
name=spi0
base=0xfe204000
irq=150
input_clock=500000000
bs=rpanic=48,tpanic=16
dma_attach_opts=num_cbs=256,range_min=0,range_max=14,typed_mem=sysram&below1G
dma_thld=4

[dev]
parent_busno=0
devno=0
name=dev0
clock_rate=17000000
cpha=0
cpol=0
bit_order=msb
word_width=8
idle_insert=1

# If SPI1 is used (currently not supported)
# the following 2 commands must be done before
# starting the spi device to set the correct
# mode for SPI1
# gpio-bcm2711 set 16,17,18 a4 pu
# gpio-bcm2711 set 19,20,21 a4 pn