# can0: Waveshare 2-CH CAN FD HAT CAN0 -> SPI0
hint.mcp25xxfd.0.dev="/dev/io-spi/spi0/dev0"
hint.mcp25xxfd.0.gpio="25"
hint.mcp25xxfd.0.bps="500000"
#hint.mcp25xxfd.0.fd="on"

# can1: HAT CAN1 -> SPI1 (Requires update to spi config)
hint.mcp25xxfd.1.dev="/dev/io-spi/spi1/dev0"
hint.mcp25xxfd.1.gpio="24"
hint.mcp25xxfd.1.bps="500000"
