# Below is a SPI configuration which supports both CAN0 and CAN1
# in order for it to work we need to enable the interrupt and set the correct
# modes for gpio-rpi which can be added before starting SPI in post_start.sh

#### Copy the following and uncomment
# # Enable RPI MSIX SPI1 interrupts
# msix-rp1 --mode=config 20lll
# gpio-rp1 set 19-21 a4 pu # SPI1 Data/Clk pins
# gpio-rp1 set 17-18 a4 pd # SP1 Chip Select pins
#### END of copy

[globals]
verbose=5

[bus]
busno=0
name=spi0
base=0x1f00050000
irq=179
input_clock=200000000
bs=cs_max=1

[bus]
busno=1
name=spi1
base=0x1f00054000
irq=180
input_clock=200000000
bs=cs_max=1

# RPI5 uses a lower clock speed to avoid dropping frames
[dev]
parent_busno=0
devno=0
name=dev0
clock_rate=4000000
cpha=0
cpol=0
bit_order=msb
word_width=8
idle_insert=1

[dev]
parent_busno=1
devno=0
name=dev0
clock_rate=4000000
cpha=0
cpol=0
bit_order=msb
word_width=8
idle_insert=1